site_name: Moje projekty
site_author: Katarzyna Gustak
site_url: https://katarzynagustak.github.io/ds_ai_portfolio
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!
    
repo_name: KatarzynaGustak/ds_ai_portfolio
repo_url: https://github.com/KatarzynaGustak/ds_ai_portfolio


theme:
  name: material
  palette:
    primary: green

markdown_extensions:
  - attr_list
  - md_in_html 

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "LinguaTales – Learn Languages Through AI-Generated Stories": linguatales/index.md
- Poprzednie projekty:
  - "Biegowy Prognozator - Predictive App for Runners": halfmarathon_time/index.md
  - "Color Your Creative Pattern": coloring_books/index.md
  - "Synergy Squad Application": Synergy_Squad_App/index.md
  - "Audio Notes Application": audio_notes/index.md
  - "Friends Course Application": welcome_survey/index.md
  - "Daily Lifestyle and Academic Performance of Students": student_lifestyle/index.md
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md